import type { Metadata } from "next";
import "./globals.scss";




export const metadata: Metadata = {
  title: "Scheduler",
  description: "Generated by create next app",
  icons: "./images/favicon.ico",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`poppins antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
